= Bash
:experimental:

== Általános

[source, bash]
----
dpkg-reconfigure tzdata
dpkg-reconfigure locales
update-alternatives --config editor
----

.tree paranccsal
[source, bash]
find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

.tree paranccsal, - git mappa, + fájlok
[source, bash]
find . -not -path "./.git/*" | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"

.naptár
[source, bash]
cal | sed "s/^/ /;s/$/ /;s/ $(date +%e) / $(date +%e | sed 's/./#/g') /"

.fájlok típus szerint
[source, bash]
find ${*-.} -type f | xargs file | awk -F, '{print $1}' | awk '{$1=NULL;print $0}' | sort | uniq -c | sort -nr

.könyvtár megosztás http-n a 8000 porton
[source, bash]
python -c "import SimpleHTTPServer;SimpleHTTPServer.test()"


== Billentyű kombináció

[%header]
|===
| Kombináció | Leírás
| kbd:[CTRL + r] | rekurzív keresés a parancs historyban
| kbd:[CTRL + l] | konzol ablak törlése/frissítése
| kbd:[CTRL + u] | kurzortól balra eső rész levágása
| kbd:[CTRL + k] | kurzortól jobbra eső rész levágása
| kbd:[CTRL + a] | sor elejére ugrás
| kbd:[CTRL + e] | sor végére ugrás
| kbd:[CTRL + INSERT] | vágólapra másolás
| kbd:[SHIFT + INSERT] | vágólapról beillesztés
| kbd:[ALT + .] | előző parancs első paraméterének behelyettesítése
| kbd:[ALT + *] | a beírt wildcard-ok behelyettesítése
| kbd:[CTRL + ALT + e] | alias, history, expansion alkalmazás a beírt parancson
| kbd:[CTRL + x + e] | beírt parancs szerkesztése a VISUAL-ban megadott szerkesztőben
|===


== Brace expansion

[source, bash]
----
echo _{I,want,my,money,back}
_I _want _my _money _back

echo {I,want,my,money,back}_
I_ want_ my_ money_ back_

echo _{I,want,my,money,back}-
_I- _want- _my- _money- _back-

echo {5..12}
5 6 7 8 9 10 11 12

echo {1..10..2}
1 3 5 7 9

echo {c..k}
c d e f g h i j k

echo 1.{0..9}
1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9

echo {A..Z}{0..9}
A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 B0 B1 B2 B3 ...

mkdir /home/bash/test/{foo,bar,baz,dog}

somecommand -v{,,,,}
somecommand -v -v -v -v -v
----
