= Recipe


== Vodka kocka

*Hozzávalók*

* 2 zacskó tortazselé/aszpik
* fél liter vodka
* 2 evőkanál cukor


Elkészítjük a zselét (a zacskó hátulján rajta van, hogyan kell), de az előírtnál 20%-al kevesebb folyadékkal. Amikor készen van, egy téglalap alakú edénybe töltjük, de jégkockatartókba is lehet. A cukrot elkeverjük benne, majd 2-5 percet állni hagyjuk, míg le nem hül, de még nem dermed meg. Ekkor adjuk hozzá a vodkát és óvatosan elkeverjük, hűtőbe rakjuk. Megdermedés után 2x2cm-es kockákra vágjuk föl és mignon-os papíron tálaljuk.

FIGYELEM: 3-4 kocka = feles!


== Kakaós süti, a mikróból

*Hozzávalók*

* 4 evőkanál liszt
* 4 evőkanál cukor
* 2 evőkanál kakaó
* 1 (teljes)tojás
* 3 evőkanál tej
* 3 evőkanál olaj
* forma amiben beteszed a mikróba

A 4 ek. lisztet és a 2 ek. kakaót összekevered. Ezalatt a tojással a 4 ek. cukrot összekutyulod.
Ha a tojásos cukros massza már szépen összeállt, akkor azt hozzáöntöd a kakaós liszthez.
Ezt ismét összekevered. Utána megy hozzá a 3 ek. tej, majd a 3 ek. olaj, és az egészet csomómentesre kevered.
Ezt már be is teheted sütni, vagy valamibe beleöntöd(bögre, műzlistál, műanyagforma, mindegy, csak bírja a mikrohullámú sütőt).
A sütés, az 3 perc, 1000W-on (max fokozat általában). Készüléke válogatja, hogy ez hány Watt, de figyelni kell hogy dagad,
és ha már nem dagad tovább, akkor már nem kell sokáig maradnia a mikróban.
Sütés közben, körülbelül a másfélszeresére dagad... ezzel számoljatok.


== Chips


=== Kukorica chips

*Hozzávalók*

* 2 csésze (1,5 dl) előfőzött kukoricaliszt (kukoricalepény liszt néven kapható)
* 1 csésze víz
* 1/4 csésze olvasztott margarin
* 1 mokkáskanál só
* 5 mokkáskanál parmezán sajt

A sütőt beállítom 170 °C-ra. +
A hozzávalókat összegyúrom, és két lap sütőpapír közt 1,5 mm vastagra nyújtom. Fontos az egyenletes tésztavastagság, hogy mindenütt egyformán süljön át. A megadott mennyiséget egy normál méretű tepsi hátán 2 adagban lehet megsütni.
Ha kész, a felső papírt óvatosan lehúzom róla, és az alsó papírral átcsúsztatom a tepsi hátára. Ott egy éles késsel tetszőleges darabokra vágom. (Nekünk a 4 cm oldalélű négyzet nagyon bevált.)  Betolom a már meleg sütőbe és légkeveréses üzemmódban 16-17 percig sütöm. Akkor jó, ha a teteje pici aranybarna színt kap. Ha hamar kiszedjük, rágós, ha későn, nagyon sült ízű lesz.
Ha a darabok összesültek, egyszerűen széttördelem, és egy tányérra rakom. Ha több menetben készül, ugyan az a sütőpapírpár többször is felhasználható.


=== Burgonyachips light

*Hozzávalók*

* 3 nagy burgonya
* kevés olaj
* só
* provence-i fűszerkeverék (vagy tetszés szerinti más fűszer)

Meghámozzuk a burgonyákat, majd nagyon vékonyra szeleteljük. Ezután langyos vízzel leöblítjük, majd alaposan megszárítjuk. A burgonyaszeleteket egy tányérra rakjuk, olajba mártott ecsettel megkenjük, meghintjük a fűszerrel, majd megfordítjuk, és a másik oldalon is elvégezzük a műveletet. A mikrohullámú sütőt 850 Wattra állítjuk, és 4-5 percig sütjük a burgonyát. Ha ennyi idő kevésnek bizonyulna, még 1-2 perccel lehet tovább sütni.

Előkészítés: 10 perc +
Sütés: 5 perc


== Pincepörkölt

*Hozzávalók*

* 10 dkg zsír
* 1 kg marhahús
* 1 kg sertésdagadó vagy lapocka
* 20 dkg füstöltsonka
* 40 dkg vöröshagyma
* 4-5 gerezd fokhagyma
* kis tubus pirosarany
* 3 evőkanál pirospaprika
* 3 db hegyes, erős zöldpaprika
* 2 db paradicsom
* 2 dl vörösbor
* só, bors, ízlés szerint


Borbás Marcsi tudja, hogy az alapszabály mindenhol ugyanaz: ahogy a jó borhoz elengedhetetlen a jó hordó, úgy a jó pincepörkölt csak bográcsban készülhet. Mégis, ha megkívánja, egyszerűen otthon lábasban is elkészíti. Ezúttal a balatonrendesiek receptjét választotta, mert nagyon egyszerű, szinte lehetetlen elrontani, ha jó minőségűek az alapanyagok.

A pincepörkölt általában kétféle húsból készül. Marhából lehetőleg lábszárat használjunk, sertésből pedig dagadót és lapockát. A fűszerek mellett a házi füstölt szalonna is nagy szerepet játszik. Ha nincs, az sem baj: bármilyen füstölt hús megteszi, amelyik nem csontos. A siker titka a húsok rétegezése. Fontos, hogy jóféle húsokat vegyünk, Marcsi szürke marhából és mangalicából szokta főzni a pincepörköltet. Előkészítésként a húsokat nagyjából egyforma falatnyi kockákra vágja, a vöröshagymát és a szalonnát pedig apróra. A pincepörköltnél nem szükséges előre megpirítani a hagymát, mert rétegesen rakjuk a húsok közé. Amikor a hozzávalókat a bográcsba, vagy a lábosba rakosgatja, legalulra kerül a szalonna, erre a hagyma fele, aztán a marhahús jön, erre a többi hagyma, arra a sertéshús. Ezután tetejére a só, a fokhagyma és végül a csípős zöldpaprika és a cikkekre vágott paradicsom. Mielőtt felteszi főni, felönti annyi vízzel, hogy éppen csak ellepje a húst. Amikor már rotyog és kezdi elfőni a levét, jóféle borocskát önt rá. Az őrölt pirospaprikát csak a vége felé, amikor már majdnem puha a hús, akkor adja hozzá. Ha kiadósabbra, bővebb szafttal készíti, akkor, amíg főnek a húsok, meghámoz fejenként egy-két krumplit, felvágja és a lábas (vagy bogrács) tetején szépen elrendezi a hasábokat. Még húsz percig főzi kislángon, és már készen is van. Azt tanácsolja, hogy friss, ropogós, saját készítésű fehér kenyérrel fogyasszuk. Az igazi pincepörkölthöz persze egy kis éneklés is kell, attól csak jobban esik az étel.



== A málé

*Hozzávalók* (egy tepsihez)

* 50 dkg kukoricaliszt
* forró víz


Leginkább csak hallomásból ismert, lassan feledésbe merülő népi ételünk a málé, amit a háziasszonyok évszázadokon át készítettek. A málé elnevezés a legelterjedtebb, de vidékenként más neveken is ismeretes.
Tésztáját is változatosan készítik, ahány vidék, annyiféle málé. Van ahol a kukoricaliszt helyett búza-, vagy hajdinalisztből sütik, tésztájába még tököt, almát is kevernek. Az ízletes, édeskés lepény kedvelt reggeli vagy uzsonna lehet. Lekvárral leöntve, töltve, gyümölccsel tálalva egészséges finomság, amit a gyerekek is szívesen majszolnak.

Egy tálba öntött kukoricalisztbe apránként keverjünk forró vizet addig, míg galuskasűrűségű tésztamasszát kapunk. Ekkor a tálat letakarjuk, és legalább 6-8 órán át meleg helyen pihentetjük. Egy, a gáz- vagy villanysütőhöz járó, lapos tepsit, vagy két kisebb peremes tepsit kivajazunk, és beleöntjük a tésztát. Elsimítjuk a tetejét, és 20-30 perc alatt közepesen meleg sütőben megsütjük a málét. Akkor jó, ha a széle kissé megpirul. Tűpróbával ellenőrizhetjük, hogy átsült-e a közepe is, Ha kihűlt, tetszés szerint felszeleteljük.
Azért fontos, hogy betartsuk a pihentetési időt, mert az alatt a kukoricaliszt keményítőtartalma részben átalakul, lebomlik cukorrá, ettől lesz édes a málé.
