= Recipe


== Vodka kocka

*Hozzávalók*

* 2 zacskó tortazselé/aszpik
* fél liter vodka
* 2 evőkanál cukor


Elkészítjük a zselét (a zacskó hátulján rajta van, hogyan kell), de az előírtnál 20%-al kevesebb folyadékkal. Amikor készen van, egy téglalap alakú edénybe töltjük, de jégkockatartókba is lehet. A cukrot elkeverjük benne, majd 2-5 percet állni hagyjuk, míg le nem hül, de még nem dermed meg. Ekkor adjuk hozzá a vodkát és óvatosan elkeverjük, hűtőbe rakjuk. Megdermedés után 2x2cm-es kockákra vágjuk föl és mignon-os papíron tálaljuk.

FIGYELEM: 3-4 kocka = feles!


== Kakaós süti, a mikróból

*Hozzávalók*

* 4 evőkanál liszt
* 4 evőkanál cukor
* 2 evőkanál kakaó
* 1 (teljes)tojás
* 3 evőkanál tej
* 3 evőkanál olaj
* forma amiben beteszed a mikróba

A 4 ek. lisztet és a 2 ek. kakaót összekevered. Ezalatt a tojással a 4 ek. cukrot összekutyulod.
Ha a tojásos cukros massza már szépen összeállt, akkor azt hozzáöntöd a kakaós liszthez.
Ezt ismét összekevered. Utána megy hozzá a 3 ek. tej, majd a 3 ek. olaj, és az egészet csomómentesre kevered.
Ezt már be is teheted sütni, vagy valamibe beleöntöd(bögre, műzlistál, műanyagforma, mindegy, csak bírja a mikrohullámú sütőt).
A sütés, az 3 perc, 1000W-on (max fokozat általában). Készüléke válogatja, hogy ez hány Watt, de figyelni kell hogy dagad,
és ha már nem dagad tovább, akkor már nem kell sokáig maradnia a mikróban.
Sütés közben, körülbelül a másfélszeresére dagad... ezzel számoljatok.


== Chips


=== Kukorica chips

*Hozzávalók*

* 2 csésze (1,5 dl) előfőzött kukoricaliszt (kukoricalepény liszt néven kapható)
* 1 csésze víz
* 1/4 csésze olvasztott margarin
* 1 mokkáskanál só
* 5 mokkáskanál parmezán sajt

A sütőt beállítom 170 °C-ra. +
A hozzávalókat összegyúrom, és két lap sütőpapír közt 1,5 mm vastagra nyújtom. Fontos az egyenletes tésztavastagság, hogy mindenütt egyformán süljön át. A megadott mennyiséget egy normál méretű tepsi hátán 2 adagban lehet megsütni.
Ha kész, a felső papírt óvatosan lehúzom róla, és az alsó papírral átcsúsztatom a tepsi hátára. Ott egy éles késsel tetszőleges darabokra vágom. (Nekünk a 4 cm oldalélű négyzet nagyon bevált.)  Betolom a már meleg sütőbe és légkeveréses üzemmódban 16-17 percig sütöm. Akkor jó, ha a teteje pici aranybarna színt kap. Ha hamar kiszedjük, rágós, ha későn, nagyon sült ízű lesz.
Ha a darabok összesültek, egyszerűen széttördelem, és egy tányérra rakom. Ha több menetben készül, ugyan az a sütőpapírpár többször is felhasználható.


=== Burgonyachips light

*Hozzávalók*

* 3 nagy burgonya
* kevés olaj
* só
* provence-i fűszerkeverék (vagy tetszés szerinti más fűszer)

Meghámozzuk a burgonyákat, majd nagyon vékonyra szeleteljük. Ezután langyos vízzel leöblítjük, majd alaposan megszárítjuk. A burgonyaszeleteket egy tányérra rakjuk, olajba mártott ecsettel megkenjük, meghintjük a fűszerrel, majd megfordítjuk, és a másik oldalon is elvégezzük a műveletet. A mikrohullámú sütőt 850 Wattra állítjuk, és 4-5 percig sütjük a burgonyát. Ha ennyi idő kevésnek bizonyulna, még 1-2 perccel lehet tovább sütni.

Előkészítés: 10 perc +
Sütés: 5 perc
